const Response = require('./Response')
const Profile = require('./Profile')
const AuthInfo = require('./AuthInfo')
const ContractInfo = require('./ContractInfo')
const UserInfo = require('./UserInfo')
const PassInfo = require('./PassInfo')
const PinInfo = require('./PinInfo')
const MobilePinInfo = require('./MobilePinInfo')
const EmailSettings = require('./EmailSettings')
const NicknameInfo = require('./NicknameInfo')
const IdentificationInfo = require('./IdentificationInfo')
const Price = require('./Price')
const SmsNotification = require('./SmsNotification')
const PriorityPackage = require('./PriorityPackage')
const Identification = require('./Identification')
const WalletLimit = require('./WalletLimit')
const WalletRestriction = require('./WalletRestriction')
const Payments = require('./Payments')
const Transaction = require('./Transaction')
const Provider = require('./Provider')
const PaymentView = require('./PaymentView')
const CurrencyAmount = require('./CurrencyAmount')
const PaymentsStats = require('./PaymentsStats')
const Account = require('./Account')
const AccountOffer = require('./AccountOffer')
const PaymentMethod = require('./PaymentMethod')
const PaymentCommissionRates = require('./PaymentCommissionRates')
const PaymentDetails = require('./PaymentDetails')
const PaymentDetailsInternationalCardTransfer = require('./PaymentDetailsInternationalCardTransfer')
const PaymentDetailsBankTransfer = require('./PaymentDetailsBankTransfer')
const PaymentDetailsBankDetailsTransfer = require('./PaymentDetailsBankDetailsTransfer')
const PaymentRequest = require('./PaymentRequest')
const CrossRate = require('./CrossRate')
const WebhookInfo = require('./WebhookInfo')
const Update = require('./Update')
const Payment = require('./Payment')

class Types {}
Types.Response = Response
Types.Profile = Profile
Types.AuthInfo = AuthInfo
Types.ContractInfo = ContractInfo
Types.UserInfo = UserInfo
Types.PassInfo = PassInfo
Types.PinInfo = PinInfo
Types.MobilePinInfo = MobilePinInfo
Types.EmailSettings = EmailSettings
Types.NicknameInfo = NicknameInfo
Types.IdentificationInfo = IdentificationInfo
Types.Price = Price
Types.SmsNotification = SmsNotification
Types.PriorityPackage = PriorityPackage
Types.Identification = Identification
Types.WalletLimit = WalletLimit
Types.WalletRestriction = WalletRestriction
Types.Payments = Payments
Types.Transaction = Transaction
Types.Provider = Provider
Types.PaymentView = PaymentView
Types.CurrencyAmount = CurrencyAmount
Types.PaymentsStats = PaymentsStats
Types.Account = Account
Types.AccountOffer = AccountOffer
Types.PaymentMethod = PaymentMethod
Types.PaymentCommissionRates = PaymentCommissionRates
Types.PaymentDetails = PaymentDetails
Types.PaymentDetailsInternationalCardTransfer = PaymentDetailsInternationalCardTransfer
Types.PaymentDetailsBankTransfer = PaymentDetailsBankTransfer
Types.PaymentDetailsBankDetailsTransfer = PaymentDetailsBankDetailsTransfer
Types.PaymentRequest = PaymentRequest
Types.CrossRate = CrossRate
Types.WebhookInfo = WebhookInfo
Types.Update = Update
Types.Payment = Payment

module.exports = Types
